#!/bin/bash
### BEGIN INIT INFO
# Provides:       rserve-startup
# Required-Start: 
# Required-Stop:  
# Should-Start:   
# Should-Stop:    
# Default-Start:  2 3 4 5
# Default-Stop:   
# Description:    Start the R server backend that produces plots for the website.
### END INIT INFO
sudo -u jenkins R_HOME=/usr/lib/R /usr/lib/R/bin/Rserve --no-save

